### ISSUE TITLE
arcsys2の `ipt_files` branchについて

### ISSUE THREAD

**Issue by forno** [agrirobo/CAD#1]
Hi.
なんでトランスポート機能とか使わなかったんだろうとか素朴な疑問を覚えつつ。
arcsys2に存在する `ipt_files` branchの取り扱いをどうするか聞きにきましたー。

ファイルをこっちに移して消すのか、そのまま消すのか、あるいはその他か、何らかの対応をおねがいしますー。

**Comment by shimoe** [comment]
そういえばそんなbranchありましたね。すっかり忘れて確認もしてなかった。申し訳ない。

Gitの機能についてはまだ不勉強な点が多いのでご教授願えるとありがたいです。
どっちかに統合することにはなるだろうけれどもそれはまた工房で話してからでいいでしょう。

**Comment by forno** [comment]
あ、そっちのブランチいらないです `ipt_files` ブランチをぶっ飛ばしてCADの方に送りつけてくだされば大丈夫です。

**Comment by forno** [comment]
多分CADの方に移し終わってるというか、上がってるファイルが古すぎてなんの役にも立たないはずなので、ipt_filesブランチを破棄しますー。
